import AppQueryClientProvider from "@/components/providers/AppQueryClientProvider"
import LocalizationProviderMUIProvider from "@/components/providers/LocalizationProviderMUIDatePicker"
import theme from "@/constants/theme/clientTheme"
import InitColorSchemeScript from "@mui/material/InitColorSchemeScript"
import { ThemeProvider } from "@mui/material/styles"
import type { Metadata } from "next"
import "./globals.css"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: LayoutProps<"/[lang]/dashboard">) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={"antialiased"}>
        <InitColorSchemeScript attribute="class" />
        <ThemeProvider theme={theme} defaultMode="light">
          <LocalizationProviderMUIProvider>
            <AppQueryClientProvider>{children}</AppQueryClientProvider>
          </LocalizationProviderMUIProvider>
        </ThemeProvider>
      </body>
    </html>
  )
}

export async function generateStaticParams() {
  return [
    { lang: "en-US" },
    { lang: "vi-VN" },
    // add other supported languages
  ]
}
