import AppQueryClientProvider from "@/components/providers/AppQueryClientProvider"
import LocalizationProviderMUIProvider from "@/components/providers/LocalizationProviderMUIDatePicker"
import theme from "@/constants/theme/clientTheme"
import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter"
import InitColorSchemeScript from "@mui/material/InitColorSchemeScript"
import { ThemeProvider } from "@mui/material/styles"
import type { Metadata } from "next"
import { LayoutProps } from "../../../.next/types/app/[lang]/layout"
import "./globals.css"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }: LayoutProps) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={"antialiased"}>
        <InitColorSchemeScript attribute="class" />
        <AppRouterCacheProvider>
          <ThemeProvider theme={theme} defaultMode="light">
            <LocalizationProviderMUIProvider>
              <AppQueryClientProvider>{children}</AppQueryClientProvider>
            </LocalizationProviderMUIProvider>
          </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  )
}
